name: packedoo_app_material
description: Packedoo mobile app (Material)

version: 1.3.3+33

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  firebase_core: ^0.4.0
  cloud_firestore: ^0.12.9
  firebase_storage: ^3.0.6
  google_sign_in: ^4.0.7
  firebase_auth: ^0.14.0
  firebase_crashlytics: ^0.1.0
  firebase_performance: ^0.3.0
  firebase_messaging: ^6.0.9
  cloud_functions: ^0.4.1
  firebase_analytics: ^5.0.11
  
  cupertino_icons: ^0.1.2
  intl: ^0.16.0
  intl_translation: ^0.17.7
  provider: ^4.0.4
  cached_network_image: 2.0.0-rc.1
  url_launcher: ^5.2.3
  flutter_rating_bar: ^1.3.0
  http: ^0.12.0
  image_picker: ^0.6.3
  permission_handler: ^3.3.0
  image_cropper: ^1.1.0
  flutter_google_places: ^0.2.3
  flutter_app_badger: ^1.1.2
  geolocator: ^5.1.3
  mime: ^0.9.6
  uuid: ^2.0.2
  location_permissions: ^2.0.2
  flutter_image_compress: ^0.6.3
  path_provider: ^1.2.0
  pin_code_text_field: ^1.3.7
  quiver: ^2.0.5
  flutter_slidable: ^0.5.4
  flutter_device_locale: ^0.3.4+1
  rxdart: ^0.23.1
  intl_phone_number_input: ^0.3.0

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: false
  image_path: "assets/icons/app_icon_512.png"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  adaptive_icon_background: "assets/icons/app_icon_background.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_title_img.png  
    - assets/images/google_login_button_ru.png
    - assets/images/google_login_button_en.png
    - assets/images/google_logo.png
    - assets/images/btn_google_logo.png
    - assets/images/no_photo_placeholder.png
    - assets/images/default_user.png
    - assets/images/login_buttons/google_en.png
    - assets/images/login_buttons/google_ru.png
    - assets/images/login_buttons/email_en.png
    - assets/images/login_buttons/email_ru.png
    - assets/images/blue_circle.png
    - assets/images/red_circle.png
    - assets/images/green_circle.png
    - assets/images/packedoo_icon.png
    - assets/images/size_l.png
    - assets/images/size_s.png
    - assets/images/size_m.png
    - assets/images/size_xl.png
    - assets/images/size_xxl.png
  